version: '3'

services:
  immoscout-db:
    image: mysql:5
    networks:
      - immoscout
    ports:
      - 3306:3306
    volumes:
      - /home/ec2-user/mysqlDb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=apartments
      - MYSQL_ROOT_PASSWORD=mypassword

  immoscout-rest:
    image: 516377452114.dkr.ecr.eu-central-1.amazonaws.com/immoscout-rest
    networks:
      - immoscout
    ports:
      - 8080:8080
    environment:
      - MYSQL_DATABASE=apartments
      - MYSQL_HOST=immoscout-db
      - MYSQL_ROOT_PASSWORD=mypassword
    depends_on:
      - immoscout-db

  immoscout-front:
    image: 516377452114.dkr.ecr.eu-central-1.amazonaws.com/immoscout-front
    networks:
      - immoscout
    ports:
      - 80:80

  immoscout-crawler:
    image: 516377452114.dkr.ecr.eu-central-1.amazonaws.com/immoscout-crawler
    networks:
      - immoscout
    volumes:
      - /home/ec2-user/crawlerConfig:/usr/local/bin/crawler/configFile
    environment:
      - NODE_ENV=production
    depends_on:
      - immoscout-db


networks:
  immoscout: